/* Generated By:JJTree: Do not edit this line. ASTDefaultStmt.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package analyzer.ast;

public
class ASTDefaultStmt extends SimpleNode {
  public ASTDefaultStmt(int id) {
    super(id);
  }

  public ASTDefaultStmt(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bba37da96e9862256e2d380c5080ecc4 (do not edit this line) */
